# Generated by Django 3.2 on 2021-04-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=50)),
                ('account_no', models.DecimalField(decimal_places=0, max_digits=15, unique=True)),
                ('mobile_no', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('aadhar_number', models.DecimalField(decimal_places=0, max_digits=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Bank.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Bank.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]