# Generated by Django 3.2 on 2021-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]